packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: set this to true or false
  sharp: set this to true or false
onlyBuiltDependencies:
  - esbuild
  - lightningcss
  - sharp
  - "@tailwindcss/oxide"
overrides:
  rollup: "npm:@rollup/wasm-node@^4.28.1"
  "@types/react": "19.0.0"
  "@types/react-dom": "19.0.0"
